version: 0.2
CANONICAL:
    DATABASE_NAME: ABBV_SMDW_DEV
    SCHEMA_NAME: DIL
    ROLE_NAME: 'ROLE'
    MDM_CUSTOMER_MASTER:
        - MDMID: [value,NUMBER,PARTY_ID,NA]
        - Name: [value,STRING,PARTY_NAME,NA]
        - Status: [value,STRING,PARTY_STATUS_DESCRIPTION,NA]
        - uri: [NA,STRING,HCO_RELTIO_URI,NA]
        - Prefix: [value,STRING,NAME_PREFIX_CODE,NA]
        - Title: [value,STRING,JOB_TITLE,NA]
        - Title: [value,STRING,TITLE_DESCRIPTION,NA]
        - Title: [value,STRING,TITLE_CODE,NA]
        - FirstName: [value,STRING,FIRST_NAME,NA]
        - MiddleName: [value,STRING,MIDDLE_NAME,NA]
        - LastName: [value,STRING,LAST_NAME,NA]
        - NameSuffix: [value,STRING,NAME_SUFFIX_CODE,NA]
        - DoNotContact: [value,STRING,No_Access_Flag,NA]
        - PrivacyPreferences: [NA,string,NA,NA]
        - PDRPComplianceDate: [value,string,RX_DATA_RESTRCTN_COMPLIANCE_DT,PrivacyPreferences]
        - PDRPDate: [value,string,RX_DATA_RESTRCTN_SIGNUP_DATE,PrivacyPreferences]
        - NoWebFlag: [value,string,NO_WEB_FLAG,PrivacyPreferences]
        - Gender: [value,STRING,GENDER_DESCRIPTION,NA]
        - DoB: [value,STRING,BIRTH_DATE,NA]
        - YoB: [value,STRING,BIRTH_YEAR,NA]
        - BirthCountry: [value,STRING,BIRTH_COUNTRY_NAME,NA]
        - TypeOfPractice: [value,STRING,PRACTICE_TYPE,NA]
        - MajorProfessionalActivity: [value,STRING,MAJOR_PROFESSIONAL_ACTIVITY,NA]
        - Sanction: [NA,string,NA,NA]
        - ActionCode: [value,string,DEA_REVOKED_FLAG,Sanction]
        - ActionDescription: [value,string,SANCTION_REASON,Sanction]
        - SanctionPeriodStartDate: [value,string,SANCTION_START_DATE,Sanction]
        - SanctionPeriodEndDate: [value,string,SANCTION_END_DATE,Sanction]
        - PresentEmployment: [value,STRING,PRESENT_EMPLOYMENT,NA]
        - ProfType: [value,STRING,PROFESSIONAL_TYPE_CODE,NA]
        - ProfType: [value,STRING,PROFESSIONAL_TYPE_DESCRIPTION,NA]
        - ABSCalculationDate: [value,STRING,EFFECTIVE_DATE,NA]
        - ABSCode: [value,STRING,SPECIALTY_CODE,NA]
        - KaiserProvider: [value,STRING,KAISER_FLAG,NA]
        - PrescriberStatus: [value,STRING,PRESCRIBER_STATUS,NA]
        - Retired: [value,STRING,RETIRED_FLAG,NA]
        - SFAFlag: [value,STRING,SFA_FLAG,NA]
        - NoOfOffices: [value,STRING,NUMBER_OF_OFFICES,NA]
        - SecondaryDegree: [value,STRING,SECONDARY_DEGREE_CODE,NA]
        - ABSCode: [value,STRING,ABS,NA]
        - ABSCode: [value,STRING,MAJOR_PROF_ACTIVITY,NA]
        - Employer: [value,STRING,EMPLOYER_NAME,NA]
        - Default : [[URI,HCO_RELTION_URI],[HCP, PARTY_SUPER_TYPE_CODE],[Personal, PARTY_SUPER_TYPE_DESCRIPTION]]
    MDM_ADDRESS_MASTER:
        - MDMID: [value,number,MDM_ID,NA]
        - Address: [label,varchar,Address_label,NA]
        - Addressline1: [value,varchar,Address_line1,Address]
        - Addressline2: [value,varchar,Address_line2,Address]
        - AddressLoadDate: [value,varchar,AddressLoadDate,Address]
        - AddressScore: [value,float ,AddressScore,Address]
        - AddressStatus: [value,varchar,AddressStatus,Address]
        - AddressType: [value,varchar,AddressType,Address]
        - City: [value,varchar,City,Address]
        - Country: [value,varchar,Country,Address]
        - DEA: [NA,varchar,DEA,Address]
        - DEAExpirationDate: [value,varchar,DEAExpirationDate,DEA]
        - DEAStatus: [value,varchar,DEAStatus,DEA]
        - GeoLocation: [label,varchar,GeoLocation_lebel,Address]
        - GeoAccuracy: [value,varchar,GeoAccuracy,GeoLocation]
        - Latitude: [value,varchar,Latitude,GeoLocation]
        - Longitude: [value,varchar,Longitude,GeoLocation]
        - HCOAddressScore: [value,varchar,HCOAddressScore,GeoLocation]
        - PreferredPhysicalAddressFlag: [value,varchar,PreferredPhysicalAddressFlag,GeoLocation]
        - Premise: [value,varchar,Premise,GeoLocation]
        - StateProvince: [value,varchar,StateProvince,GeoLocation]
        - Street: [value,varchar,Street,GeoLocation]
        - SubAdministrativeArea: [value,varchar,SubAdministrativeArea,GeoLocation]
        - VerificationStatus: [value,varchar,VerificationStatus,GeoLocation]
        - VerificationStatusDetails: [value,varchar,VerificationStatusDetails,GeoLocation]
        - Zip: [value,varchar,Zip_lebel,GeoLocation]
        - Zip4: [value,number,Zip4,Zip]
        - Zip5: [value,number,Zip5,Zip]
    MDM_CUSTOMER_EDUCATION:
        - MDMID: [value,NUMBER,PARTY_ID,NA]
        - Education: [NA,string,Education,NA]
        - SchoolName: [value,STRING,SCHOOL_NAME,Education]
        - Type: [value,STRING,SCHOOL_TYPE,Education]
        - SchoolCode: [value,STRING,SCHOOL_CODE,Education]
        - YearsInProgram: [value,STRING,YEARS_IN_PROGRAM,Education]
        - GraduationYear: [value,STRING,GRADUATION_YEAR,Education]
        - StartYear: [value,STRING,START_YEAR,Education]
        - EndYear: [value,STRING,END_YEAR,Education]
        - FieldofStudy: [value,STRING,FIELD_OF_STUDY,Education]
        - ConfirmationFlag: [value,STRING,CONFIRMATION_FLAG,Education]
        - State: [value,STRING,GRADUATION_STATE_CODE,Education]
        - EducationEndDate: [value,STRING,EDUCATION_END_DATE,Education]
        - EducationEndDate: [value,STRING,END_DATE,Education]
    MDM_CUSTOMER_SALESTEAM:
        - MDMID: [value,STRING,PARTY_ID,NA]
        - TeamAssignment: [NA,STRING,AMDM_PHYSICIAN_ID,NA]
        - AMDMID: [value,STRING,AMDM_PHYSICIAN_ID,TeamAssignment]
        - Address: ['NA',STRING,Address,TeamAssignment]
        - AddressLine1: [value,STRING,ADDRRESS_LINE1,Address]
        - AddressLine2: [value,STRING,ADDRRESS_LINE2,Address]
        - City: [value,STRING,CITY,Address]
        - StateProvince: [value,STRING,STATE,Address]
        - Zip4: [value,STRING,POSTAL_CODE,Address]
        - Zip5: [value,STRING,POSTAL_EXT,Address]
        - Phone: [NA,STRING,PRIMARY_PHONE,TeamAssignment]
        - Number: [value,STRING,PRIMARY_PHONE,Phone]
        - Type: [value,STRING,PHONE_TYPE,Phone]
        - Email: [NA,STRING,EMAIL,TeamAssignment]
        - Email_1: [value,STRING,EMAIL,Email]
        - BusinessUnit: [value,STRING,BUSINESS_INIT,TeamAssignment]
        - CalledOnStatus: [value,STRING,CALLED_ON_STATUS,TeamAssignment]
        - SalesTeam: [value,STRING,SALES_TEAM_CD,TeamAssignment ]
    MDM_MULTI_SPECIALITY:
        - MDMID: [value,NUMBER,PARTY_ID,NA]
        - Specialities: [NA,STRING,SPECIALTY_CODE,NA]
        - Specialty: [value,STRING,SPECIALTY_CODE,Specialities]
        - SpecialtyType: [value,STRING,SPECIALTY_TYPE,Specialities]
        - SpecialtyDescription: [value,STRING,SPECIALTY_DESCRIPTION,Specialities]
        - ABSCalculationDate: [value,STRING,ABS_CALCULATION_DATE,NA]
        - ABSCode: [value,STRING,ABS_CODE,NA]
    MDM_IDENTIFIER:
        - MDMID: [value,NUMBER,PARTY_ID,NA]
        - Type: [value,STRING,IDENTIFIER_TYPE_DESCRIPTION,NA]
        - ID: [value,STRING,IDENTIFIER_VALUE_TEXT,NA]
        - uri: [uri,STRING,IDENTIFIER_URI,NA]
    MDM_CUSTOMER_CERTIFICATE:
        - MDMID: [value,string,MDMID,NA]
        - Certificates: [NA,string,NA,NA]
        - CertificateId: [value,string,CERTIFICATE_ID,Certificates]
        - Name: [value,string,OTHER_NAME,Certificates]
        - BoardId: [value,string,BOARD_ID,Certificates]
        - BoardName: [value,string,BOARD_NAME,Certificates]
        - Specialty: [value,string,Specialty,Certificates]
        - InternalHCPStatus: [value,string,INTERNAL_HCPSTATUS,Certificates]
        - InternalHCPInactiveReasonCode: [value,string,INTERNAL_HCPINACTIVE_REASON_CODE,Certificates]
        - InternalSamplingStatus: [value,string,INTERNAL_SAMPLING_STATUS,Certificates]
        - PVSEligibilty: [value,string,OTHER_PVSELIGIBILTY,Certificates]
        - IssueDate: [value,string,CERTIFICATE_ISSUE_DATE,Certificates]
    MDM_CUSTOMER_TAXONOMY:
        - MDMID: [value,string,MDMID,NA]
        - Taxonomy: [NA,string,NA,NA]
        - Type: [value,string,TAXONOMY_TYPE,Taxonomy]
        - Group: [value,string,TAXONOMY_GROUP,Taxonomy]
        - ProviderType: [value,string,TAXONOMY_PROVIDER_TYPE,Taxonomy]
        - Classification: [value,string,TAXONOMY_CLASSIFICATION,Taxonomy]
        - Specialization: [value,string,TAXONOMY_SPECIALIZATION,Taxonomy]
        - StateCode: [value,string,STATE_CODE,Taxonomy]
        - Priority: [value,string,TAXONOMY_PRIORITY,Taxonomy]
        - TaxonomyStateCode: [value,string,TAXONOMY_STATE_CODE,Taxonomy]
