version: 0.2
CANONICAL:
    DATABASE_NAME: ABBV_SMDW_DEV
    SCHEMA_NAME: DIL
    ROLE_NAME: 'ROLE'
    MDM_CUSTOMER_MASTER:
        - MDMID: [value,string]
        - ABSCalculationDate: [value,string]
        - ABSCode: [value,string]
        - Degree: [value,string]
        - Name: [value,string]
        - FirstName: [value,string]
        - Middlename: [value,string]
        - LastName: [value,string]
        - Title: [value,string]
        - Prefix: [value,string]
        - NameSuffix: [value,string]
        - Gender: [value,string]
        - DoB: [value,string]
        - YoB: [value,string]
        - PaymentIndicator: [value,string]
        - KaiserProvider: [value,string]
        - DoNotContact: [value,string]
        - PrescriberStatus: [value,string]
        - PresumedDead: [value,string]
        - ProfType: [value,string]
        - TypeOfPractice: [value,string]
        - MajorProfessionalActivity: [value,string]
        - PresentEmployment: [value,string]
        - Employer: [value,string]
        - DeceasedFlag: [value,string]
        - RestrictedState: [value,string]
        - NextRecentFormerName: [value,string]
        - NoOfOffices: [value,string]
        - SecondaryDegree: [value,string]
        - SFAFlag: [value,string]
        - Retired: [value,string]
        - Status: [value,string]
    MDM_ADDRESS_MASTER:
        - MDM_ID: [value,string]
        - Address: [lable1,string]
        - AddressLine1: [value,string]
        - AddressLine2: [value,string]
        - AddressLoadDate: [value,string]
        - AddressScore: [value,string]
        - AddressStatus: [value,string]
        - AddressType: [value,string]
        - City: [value,string]
        - Country: [value,string]
        - DEA: [value,string]
        - DEAExpirationDate: [value,string]
        - DEAStatus: [value,string]
        - GeoLocation: [label,string]
        - GeoAccuracy: [value,string]
        - Latitude: [value,string]
        - Longitude: [value,string]
        - HCOAddressScore: [value,string]
        - PreferredPhysicalAddressFlag: [value,string]
        - Premise: [value,string]
        - StateProvince: [value,string]
        - Street: [value,string]
        - SubAdministrativeArea: [value,string]
        - VerificationStatus: [value,string]
        - VerificationStatusDetails: [value,string]
        - Zip: [value,string]
        - Zip4: [value,string]
        - Zip5: [value,string]

