version: 0.2
CANONICAL-MDM:
    DATABASE_NAME: ABBV_SMDW_DEV
    SCHEMA_NAME: MDM
    ROLE_NAME: 'ABBV_SMDW_D_ENGG_BTS_PS_INTG_511'
    warehouse: 
        XSMALL: 'ABBV_SMDW_DEV_BTS_INT_READ_WH01'
        SMALL: 'ABBV_SMDW_DEV_BTS_INT_READ_WH01'
        MEDIUM: 'ABBV_SMDW_DEV_BTS_INT_READ_WH01'
      
    MDM_CUSTOMER_MASTER:
        - MDMID: [value,NUMBER,PARTY_ID,NA]
        - Name: [value,STRING,PARTY_NAME,NA]
        - Status: [value,STRING,PARTY_STATUS_DESCRIPTION,NA]
        - uri: [NA,STRING,HCO_RELTIO_URI,NA]
        - Prefix: [value,STRING,NAME_PREFIX_CODE,NA]
        - Title: [value,STRING,JOB_TITLE,NA]
        - Title: [value,STRING,TITLE_DESCRIPTION,NA]
        - Title: [value,STRING,TITLE_CODE,NA]
        - FirstName: [value,STRING,FIRST_NAME,NA]
        - MiddleName: [value,STRING,MIDDLE_NAME,NA]
        - LastName: [value,STRING,LAST_NAME,NA]
        - NameSuffix: [value,STRING,NAME_SUFFIX_CODE,NA]
        - DoNotContact: [value,STRING,No_Access_Flag,NA]
        - PrivacyPreferences: [NA,string,NA,NA]
        - PDRPComplianceDate: [value,string,RX_DATA_RESTRCTN_COMPLIANCE_DT,PrivacyPreferences]
        - PDRPDate: [value,string,RX_DATA_RESTRCTN_SIGNUP_DATE,PrivacyPreferences]
        - NoWebFlag: [value,string,NO_WEB_FLAG,PrivacyPreferences]
        - Gender: [value,STRING,GENDER_DESCRIPTION,NA]
        - DoB: [value,STRING,BIRTH_DATE,NA]
        - YoB: [value,STRING,BIRTH_YEAR,NA]
        - BirthCountry: [value,STRING,BIRTH_COUNTRY_NAME,NA]
        - TypeOfPractice: [value,STRING,PRACTICE_TYPE,NA]
        - MajorProfessionalActivity: [value,STRING,MAJOR_PROFESSIONAL_ACTIVITY,NA]
        - Sanction: [NA,string,NA,NA]
        - ActionCode: [value,string,DEA_REVOKED_FLAG,Sanction]
        - ActionDescription: [value,string,SANCTION_REASON,Sanction]
        - SanctionPeriodStartDate: [value,string,SANCTION_START_DATE,Sanction]
        - SanctionPeriodEndDate: [value,string,SANCTION_END_DATE,Sanction]
        - PresentEmployment: [value,STRING,PRESENT_EMPLOYMENT,NA]
        - ProfType: [value,STRING,PROFESSIONAL_TYPE_CODE,NA]
        - ProfType: [value,STRING,PROFESSIONAL_TYPE_DESCRIPTION,NA]
        - ABSCalculationDate: [value,STRING,EFFECTIVE_DATE,NA]
        - ABSCode: [value,STRING,SPECIALTY_CODE,NA]
        - KaiserProvider: [value,STRING,KAISER_FLAG,NA]
        - PrescriberStatus: [value,STRING,PRESCRIBER_STATUS,NA]
        - Retired: [value,STRING,RETIRED_FLAG,NA]
        - SFAFlag: [value,STRING,SFA_FLAG,NA]
        - NoOfOffices: [value,STRING,NUMBER_OF_OFFICES,NA]
        - SecondaryDegree: [value,STRING,SECONDARY_DEGREE_CODE,NA]
        - ABSCode: [value,STRING,ABS,NA]
        - ABSCode: [value,STRING,MAJOR_PROF_ACTIVITY,NA]
        - Employer: [value,STRING,EMPLOYER_NAME,NA]
        - Default : [["'HCP'", PARTY_SUPER_TYPE_CODE],["'Personal'", PARTY_SUPER_TYPE_DESCRIPTION]]
    MDM_CUSTOMER_ADDRESS_MASTER:
        - MDMID: [value,number,PARTY_ID,NA]
        - Address: [NA,varchar,Address_label,NA]
        - attributeURIs: [value,string,ADDRESS_ID,Address]
        - Addressline1: [value,varchar,Address_line1,Address]
        - Addressline2: [value,varchar,Address_line2,Address]
        - AddressLoadDate: [value,varchar,MDM_CREATED_DATE,Address]
        - AddressScore: [value,float ,Address_Score,Address]
        - AddressStatus: [value,varchar,Address_Status_code,Address]
        - AddressStatus: [value,varchar,Address_Status_description,Address]
        - AddressType: [value,varchar,Address_Type_code,Address]
        - AddressType: [value,varchar,Address_Type_description,Address]
        - City: [value,varchar,City_name,Address]
        - Country: [value,varchar,Country_code,Address]
        - DEA: [NA,varchar,DEA,Address]
        - DEAExpirationDate: [NA,varchar,DEAExpirationDate,DEA]
        - DEAStatus: [NA,varchar,DEAStatus,DEA]  # Check this column if we needed 
        - GeoLocation: [NA,varchar,GeoLocation,Address] # Check this column if we needed 
        - GeoAccuracy: [value,varchar,GeoAccuracy,GeoLocation]
        - Latitude: [value,varchar,Latitude,GeoLocation]
        - Longitude: [value,varchar,Longitude,GeoLocation]
        #- HCOAddressScore: [value,varchar,HCOAddressScore,GeoLocation] # Check this column if we needed 
        #- PreferredPhysicalAddressFlag: [value,varchar,PREFERED_MAILING_INDICATOR,GeoLocation]
        - Premise: [value,varchar,Premise,GeoLocation]
        - StateProvince: [value,varchar,State_Province_CODE,GeoLocation]
        - Street: [value,varchar,Street,GeoLocation]
        - SubAdministrativeArea: [value,varchar,Sub_Administrative_Area,GeoLocation]
        #- VerificationStatus: [value,varchar,Verification_Status,GeoLocation]
        - VerificationStatusDetails: [value,varchar,ABBVIE_VERIFICATION_CODE,GeoLocation]
        #- VerificationStatusDetails: [value,varchar,ABBVIE_VERIFICATION_DESCRIPTION,GeoLocation]
        - Zip: [NA,varchar,Zip_lebel,GeoLocation] # Check this column if we needed 
        - Zip4: [value,number,POSTAL_EXTENSION_CODE,Zip]
        - Zip5: [value,number,POSTAL_CODE,Zip]
        - CountryName: [value,string,COUNTRY_NAME,Address]
        - MaximumAddressScore: [value,string,MAX_ADDRESS_SCORE,Address]
        - VendorMatchFlag: [value,string,VENDOR_MATCH_FLAG,Address]
        - SFAAddressID: [value,string,SFA_ADDRESSID,Address]
        - TasoAddressID: [value,string,TASO_ADDRESS_ID,Address]
        - FIPSCounty: [value,string,FIPS_COUNTY,Address]
        - FIPSState: [value,string,FIPS_STATE,Address]
        - FIPSCity: [value,string,FIPS_CITY,Address]
        - Region: [value,string,ADDRESS_REGION,Address]
        - Division: [value,string,ADDRESS_DIVISION,Address]
        - Group_1: [value,string,ADDRESS_GROUP,Address]  # gruop is key word in snowflake database so this is appeneded with with _1 ( it will replaced with '' in final select sql )
        - Tract: [value,string,ADDRESS_TRACT,Address]
        - Suffix: [value,string,ADDRESS_SUFFIX,Address]
        - BlockGroup: [value,string,ADDRESS_BLOCK_GROUP,Address]
        - EnumerationGroup: [value,string,ADDRESS_ENUMERATION_GROUP,Address]
        - County: [value,string,COUNTY_NAME,Address]
        - AddressFlag: [value,string,ADDRESS_IGNORED_FLAG,Address]
        #- VerificationStatus: [value,string,ABBVIE_VERIFICATION_CODE,Address]
        - AVC: [value,string,AVC_CODE,Address]
        - CarrierRoute: [value,string,CARRIER_ROUTE,Address]
        - DeliveryPointCode: [value,string,DELIVERY_POINT_CODE,Address]
        - AddressChangeDate: [value,string,ADDRESS_CHANGE_DATE,Address]
        - Default : [["'HCP'", PARTY_SUPER_TYPE_CODE],['"uri"', HCO_RELTIO_URI]]
    MDM_CUSTOMER_EDUCATION:  # filter the records uri present in the mdm_coustomer maste while insterting data to base table 
        - MDMID: [value,NUMBER,PARTY_ID,NA]
        - Education: [NA,string,Education,NA]
        - SchoolName: [value,STRING,SCHOOL_NAME,Education]
        - Type: [value,STRING,SCHOOL_TYPE,Education]
        - SchoolCode: [value,STRING,SCHOOL_CODE,Education]
        - YearsInProgram: [value,STRING,YEARS_IN_PROGRAM,Education]
        - GraduationYear: [value,STRING,GRADUATION_YEAR,Education]
        - StartYear: [value,STRING,START_YEAR,Education]
        - EndYear: [value,STRING,END_YEAR,Education]
        - FieldofStudy: [value,STRING,FIELD_OF_STUDY,Education]
        - ConfirmationFlag: [value,STRING,CONFIRMATION_FLAG,Education]
        - State: [value,STRING,STATE_CODE,Education]
        - EducationEndDate: [value,STRING,EDUCATION_END_DATE,Education]
        - EndDate: [value,STRING,END_DATE,Education]
        - SpecialtyTraining1: [value,STRING,SPECIALTY_TRAINING1,Education]
        - SpecialtyTraining2: [value,STRING,SPECIALTY_TRAINING2,Education]
        - CumulativeYearsOfTraining: [value,STRING,CUMULATIVE_YEARS_OF_TRAINING,Education]
        - SecondaryFieldofStudy: [value,STRING,SECONDARY_FIELD_OF_STUDY,Education]
        - Default : [["'HCP'", PARTY_SUPER_TYPE_CODE],['"uri"' , uri]]
    MDM_CUSTOMER_SALES_TEAM:
        - MDMID: [value,STRING,PARTY_ID,NA]
        - TeamAssignment: [NA,STRING,AMDM_PHYSICIAN_ID,NA]
        - AMDMID: [value,STRING,AMDM_PHYSICIAN_ID,TeamAssignment]
        - Address: ['NA',STRING,Address,TeamAssignment]
        - AddressLine1: [value,STRING,ADDRRESS_LINE1,Address]
        - AddressLine2: [value,STRING,ADDRRESS_LINE2,Address]
        - City: [value,STRING,CITY,Address]
        - StateProvince: [value,STRING,STATE,Address]
        - Zip4: [value,STRING,POSTAL_CODE,Address]
        - Zip5: [value,STRING,POSTAL_EXT,Address]
        - Phone: [NA,STRING,PRIMARY_PHONE,TeamAssignment]
        - Number: [value,STRING,PRIMARY_PHONE,Phone]
          #- Type: [value,STRING,PHONE_TYPE,Phone]
        - Email: [NA,STRING,EMAIL,TeamAssignment]
        - Email_1: [value,STRING,EMAIL,Email]
        - BusinessUnit: [value,STRING,BUSINESS_INIT,TeamAssignment]
        - CalledOnStatus: [value,STRING,CALLED_ON_STATUS,TeamAssignment]
        - SalesTeam: [value,STRING,SALES_TEAM_CD,TeamAssignment ]
        - WebsiteAddress: [value,STRING,WEBSITE,NA]
        - Default : [["'HCP'", PARTY_SUPER_TYPE_CODE]]
    MDM_CUSTOMER_MULTI_SPECIALTY: # depenency on cross walk
        - MDMID: [value,NUMBER,PARTY_ID,NA]
        - MDMID: [ov,BOOLEAN,PARTY_ID_OV,NA]
        - Specialities: [NA,STRING,NA,NA]
        - Specialty: [value,STRING,SPECIALTY_CODE,Specialities]
        - SpecialtyType: [value,STRING,SPECIALTY_TYPE,Specialities]
        - SpecialtyDescription: [value,STRING,SPECIALTY_DESCRIPTION,Specialities]
        - ABSCalculationDate: [value,STRING,ABS_CALCULATION_DATE,NA]
        - ABSCode: [lookupCode,STRING,ABS_CODE,NA]
        - ABSCode: [value,STRING,ABS_DESCRIPTION,NA]
        - Specialty: [uri,STRING,SPECIALTY_URI,Specialities]
        - Default : [["'HCP'", PARTY_SUPER_TYPE_CODE]]
    MDM_CUSTOMER_PRE_IDENTIFIER: # depenency on cross walk
        - MDMID: [value,NUMBER,PARTY_ID,NA]
        - MDMID: [ov,BOOLEAN,PARTY_ID_OV,NA] # we can filter this true later while taking the data to main/stg table 
        - Identifiers: [uri,string,attributes_uri,NA]
        - Type: [value,string,IDENTIFIER_TYPE_CODE,Identifiers]
        - Type: [value,string,IDENTIFIER_TYPE_DESCRIPTION,Identifiers]
        - ID: [value,string,IDENTIFIER_VALUE_TEXT,Identifiers]
        - Status: [value,string,IDENTIFIER_STATUS_CODE,Identifiers]
        - Status: [value,string,IDENTIFIER_STATUS_DESCRIPTION,Identifiers]
        - CreateDate: [value,timestamp,IDENTIFIER_EFFECTIVE_DATE,Identifiers]
        - DeactivationDate: [value,timestamp,NPI_DEACTIVATE_DATE,Identifiers]
        - DeactivationReasonCode: [value,timestamp,NPI_DEACTIVATE_REASON_CODE,Identifiers]
        - ReactivationDate: [value,timestamp,NPI_REACTIVATE_DATE,Identifiers]
        - Default : [["'HCP'",PARTY_SUPER_TYPE_CODE],['"uri"',URI,]]
    MDM_CUSTOMER_IDENTIFIER_PROFILE:
        - MDMID: [value,NUMBER,PARTY_ID,NA]
        - MDMID: [ov,BOOLEAN,PARTY_ID_OV,NA]  # we can filter this true later while taking the data to main/stg table 
        - ProfileID: [value,string,Profile_ID,NA]
        - ProfileID: [uri,string,attributes_uri,NA]
        - Default: [['"uri"' , URI]]
    MDM_CUSTOMER_LICENSE:
        - MDMID: [value,number,PARTY_ID,NA]
        - MDMID: [ov,BOOLEAN,PARTY_ID_OV,NA]  # we can filter this true later while taking the data to main/stg table 
        - License: [value,string,License_uri,NA]
        - Number: [value,string,LICENSE_NUMBER,License]
        - LicenseType: [value,string,LICENSE_TYPE_CODE,License]
        - State: [value,string,STATE_PROVINCE_CODE,License]
        - BoardCode: [value,string,STATE_BOARD_NUMBER,License]
        - Status: [value,string,LICENSE_STATUS,License]
        - ExpirationDate: [value,string,LICENSE_EXPIRATION_DATE,License]
        - VendorVerificationDate: [value,string,IDENTIFIER_EFFECTIVE_DATE,License]
        - SampleEligibility: [value,string,SAMPLING_ELIGIBILITY_FLAG,License]
        - AdjudicationCode: [value,string,SLN_ADJUDICATION_CODE,License]
        - Default: [['"uri"' , URI]]
    MDM_CUSTOMER_DEA:
        - MDMID: [value,string,PARTY_ID,NA]
        - MDMID: [ov,BOOLEAN,PARTY_ID_OV,NA]  # we can filter this true later while taking the data to main/stg table 
        - BusinessActivity: [NA,string,DEA_ACTIVITY_CODE,NA]
        - Code: [value,string,DEA_ACTIVITY_CODE,BusinessActivity]
        - Code: [value,string,DEA_ACTIVITY_DESCTIPTION,BusinessActivity]
        - SubCode: [lookupCode,string,DEA_SUB_ACTIVITY_CODE,BusinessActivity]
        - SubCode: [value,string,DEA_SUB_ACTIVITY_DESCRIPTION,BusinessActivity]
        - ScheduledDrug: [value,string,DEA_SCHEDULE_CLASS,NA]
        - Default: [['"uri"' , URI]]
    MDM_CUSTOMER_CROSS_WALK:
        - crosswalks: [Type,string,data_source_uri,crosswalks]
        - attributes: [value,string,attributes_uri,crosswalks]
        - Default: [['"uri"' , URI]]
    MDM_CUSTOMER_IDENTIFIER:
        - URI: [NA,NA,URI,NA]
        - PARTY_ID: [NA,NA,PARTY_ID,NA]
        - LICENSE_URI: [NA,NA,LICENSE_URI,NA]
        - LICENSE_NUMBER: [NA,NA,LICENSE_NUMBER,NA]
        - LICENSE_TYPE_CODE: [NA,NA,LICENSE_TYPE_CODE,NA]
        - STATE_PROVINCE_CODE: [NA,NA,STATE_PROVINCE_CODE,NA]
        - STATE_BOARD_NUMBER: [NA,NA,STATE_BOARD_NUMBER,NA]
        - LICENSE_STATUS: [NA,NA,LICENSE_STATUS,NA]
        - LICENSE_EXPIRATION_DATE: [NA,NA,LICENSE_EXPIRATION_DATE,NA]
        - IDENTIFIER_EFFECTIVE_DATE: [NA,NA,IDENTIFIER_EFFECTIVE_DATE,NA]
        - SAMPLING_ELIGIBILITY_FLAG: [NA,NA,SAMPLING_ELIGIBILITY_FLAG,NA]
        - SLN_ADJUDICATION_CODE: [NA,NA,SLN_ADJUDICATION_CODE,NA]
    # MDM_CUSTOMER_ADDRESS_XREF:
    #     - MDMID: [value,number,PARTY_ID,NA]
    #     - Address: [NA,varchar,NA,NA]
    #     - attributeURIs: [value,string,ADDRESS_ID,Address]
    #     - refRelation: [value:refRelation,string,refRelation,address]
    #     - crosswalks: ["refRelation.value",string,IDENTIFIER_TYPE_DESCRIPTION,refRelation]
    #     - attributeURIs: ["value",string,attributes_uri,crosswalks]
    #     #- crosswalks: ["value",string,IDENTIFIER_TYPE_CODE,NA]
    #     - Default : [["'HCP'", PARTY_SUPER_TYPE_CODE],['"uri"', uri]]
    MDM_CUSTOMER_CERTIFICATE:
        - MDMID: [value,string,PARTY_ID,NA]
        - Certificates: [NA,string,NA,NA]
        - CertificateId: [value,string,CERTIFICATE_ID,Certificates]
        - Name: [value,string,OTHER_NAME,Certificates]
        - BoardId: [value,string,BOARD_ID,Certificates]
        - BoardName: [value,string,BOARD_NAME,Certificates]
        - Specialty: [value,string,Specialty,Certificates]
        - InternalHCPStatus: [value,string,INTERNAL_HCPSTATUS,Certificates]
        - InternalHCPInactiveReasonCode: [value,string,INTERNAL_HCPINACTIVE_REASON_CODE,Certificates]
        - InternalSamplingStatus: [value,string,INTERNAL_SAMPLING_STATUS,Certificates]
        - PVSEligibilty: [value,string,OTHER_PVSELIGIBILTY,Certificates]
        - IssueDate: [value,string,CERTIFICATE_ISSUE_DATE,Certificates]
        - Default : [["'HCP'", PARTY_SUPER_TYPE_CODE]]  # "'HCP'" if this default for field lese '"uri"' for vriant column pick from json 
    MDM_CUSTOMER_TAXONOMY:  # depenency on cross walk
        - MDMID: [value,string,PARTY_ID,NA]
        - MDMID: [ov,BOOLEAN,PARTY_ID_OV,NA] # we can filter this true later while taking the data to main/stg table 
        - Taxonomy: [NA,string,NA,NA]
        - Type: [value,string,TAXONOMY_TYPE,Taxonomy]
        - Taxonomy: ['value[''Taxonomy'']',string,TAXONOMY_CODE,Taxonomy]
        #- Group: [value,string,TAXONOMY_GROUP,Taxonomy]
        - ProviderType: [value,string,TAXONOMY_PROVIDER_TYPE,Taxonomy]
        - Classification: [value,string,TAXONOMY_CLASSIFICATION,Taxonomy]
        - Specialization: [value,string,TAXONOMY_SPECIALIZATION,Taxonomy]
        - StateCode: [value,string,TAXONOMY_STATE_CODE,Taxonomy]
        - Taxonomy: [uri,string,TAXONOMY_URI,Taxonomy]
        - Priority: [value,string,TAXONOMY_PRIORITY,Taxonomy]
        - TaxonomyStateCode: [NA,string,TAXONOMY_STATE_CODE,Taxonomy]
        - Default : [["'HCP'", PARTY_SUPER_TYPE_CODE]]
