version: 0.2
CANONICAL:
    DATABASE_NAME: ABBV_SMDW_DEV
    SCHEMA_NAME: DIL
    ROLE_NAME: 'ROLE'
    MDM_CUSTOMER_MASTER:
        - MDMID: [value,NUMBER,PARTY_ID]
        - Name: [value,STRING,PARTY_NAME]
        - Status: [value,STRING,PARTY_STATUS_DESCRIPTION]
        - uri: [NA,STRING,HCO_RELTIO_URI  ]
        - Prefix: [value,STRING,NAME_PREFIX_CODE   ]
        - Title: [value,STRING,JOB_TITLE   ]
        - Title: [value,STRING,TITLE_DESCRIPTION   ]
        - Title: [value,STRING,TITLE_CODE   ]
        - FirstName: [value,STRING,FIRST_NAME]
        - MiddleName: [value,STRING,MIDDLE_NAME]
        - LastName: [value,STRING,LAST_NAME]
        - NameSuffix: [value,STRING,NAME_SUFFIX_CODE   ]
        - DoNotContact: [value,STRING,No_Access_Flag   ]
        - Gender: [value,STRING,GENDER_DESCRIPTION   ]
        - DoB: [value,STRING,BIRTH_DATE ]
        - YoB: [value,STRING,BIRTH_YEAR ]
        - BirthCountry: [value,STRING,BIRTH_COUNTRY_NAME  ]
        - TypeOfPractice: [value,STRING,PRACTICE_TYPE  ]
        - MajorProfessionalActivity: [value,STRING,MAJOR_PROFESSIONAL_ACTIVITY  ]
        - PresentEmployment: [value,STRING,PRESENT_EMPLOYMENT  ]
        - ProfType: [value,STRING,PROFESSIONAL_TYPE_CODE   ]
        - ProfType: [value,STRING,PROFESSIONAL_TYPE_DESCRIPTION   ]
        - ABSCalculationDate: [value,STRING,EFFECTIVE_DATE  ]
        - ABSCode: [value,STRING,SPECIALTY_CODE  ]
        - KaiserProvider: [value,STRING,KAISER_FLAG   ]
        - PrescriberStatus: [value,STRING,PRESCRIBER_STATUS  ]
        - Retired: [value,STRING,RETIRED_FLAG  ]
        - SFAFlag: [value,STRING,SFA_FLAG  ]
        - NoOfOffices: [value,STRING,NUMBER_OF_OFFICES  ]
        - SecondaryDegree: [value,STRING,SECONDARY_DEGREE_CODE  ]
        - ABSCode: [value,STRING,ABS  ]
        - ABSCode: [value,STRING,MAJOR_PROF_ACTIVITY  ]
        - Employer: [value,STRING,EMPLOYER_NAME  ]
    MDM_CUSTOMER_EDUCATION:
        - MDMID: [value,NUMBER,PARTY_ID]
        - Education: [NA,string,Education]
        - SchoolName: [value,STRING,SCHOOL_NAME]
        - SchoolType: [value,STRING,SCHOOL_TYPE]
        - SchoolCode: [value,STRING,SCHOOL_CODE]
        - YearsInProgram: [value,STRING,YEARS_IN_PROGRAM]
        - GraduationYear: [value,STRING,GRADUATION_YEAR]
        - StartYear: [value,STRING,START_YEAR]
        - EndYear: [value,STRING,END_YEAR]
        - FieldofStudy: [value,STRING,FIELD_OF_STUDY]
        - ConfirmationFlag: [value,STRING,CONFIRMATION_FLAG]
        - State: [value,STRING,GRADUATION_STATE_CODE]
        - EducationEndDate: [value,STRING,EDUCATION_END_DATE]
        - EducationEndDate: [value,STRING,END_DATE]
    MDM_CUSTOMER_SALESTEAM:
        - MDMID: [value,STRING,PARTY_ID ]
        - AMDMID: [value,STRING,AMDM_PHYSICIAN_ID ]
        - AddressLine1: [value,STRING,ADDRRESS_LINE1 ]
        - AddressLine2: [value,STRING,ADDRRESS_LINE2 ]
        - City: [value,STRING,CITY ]
        - StateProvince: [value,STRING,STATE ]
        - Zip4: [value,STRING,POSTAL_CODE ]
        - Zip5: [value,STRING,POSTAL_EXT ]
        - Phone_Number: [value,STRING,PRIMARY_PHONE ]
        - Email_value: [value,STRING,EMAIL ]
        - BusinessUnit: [value,STRING,BUSINESS_INIT ]
        - CalledOnStatus: [value,STRING,CALLED_ON_STATUS ]
        - SalesTeam: [value,STRING,SALES_TEAM_CD ]
    MDM_MULTI_SPECIALITY:
        - MDMID: [value,NUMBER,PARTY_ID]
        - Specialty: [value,STRING,SPECIALTY_CODE]
        - SpecialtyType: [value,STRING,SPECIALTY_TYPE]
        - SpecialtyDescription: [value,STRING,SPECIALTY_DESCRIPTION]
        - ABSCalculationDate: [value,STRING,ABS_CALCULATION_DATE]
        - ABSCode: [value,STRING,ABS_CODE]
    MDM_IDENTIFIER:
        - MDMID: [value,NUMBER,PARTY_ID]
        - Type: [value,STRING,IDENTIFIER_TYPE_DESCRIPTION]
        - ID: [value,STRING,IDENTIFIER_VALUE_TEXT]
        - uri: [uri,STRING,IDENTIFIER_URI]

